version: '3.8'

services:
  backend-server:
    image: 'server:latest'
    ports:
     - '8080:8080'
    build:
      context: .
    container_name: server
    depends_on:
      - flyway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  flyway:
    image: flyway/flyway:7.5.3
    command: -schemas=public -connectRetries=60 migrate
    container_name: flyway
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=admin1
      - FLYWAY_URL=jdbc:postgresql://db:5432/postgres
    volumes:
      - ./app/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

  db:
    image: 'postgres:14-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1
      - POSTGRES_DB=postgres

# save logs to file
# docker-compose -f docker-compose.yml up > file.txt